#pragma once

// 06-02-PLAN.md Task 1 (AUDIO-03, D-10, D-11) / 06-05-PLAN.md Task 3: the
// shared D-11 input-identity assertion for tests/fixtures/
// audio_aac_handwritten.mp4 -- the non-silent, non-SBR, plain-AOT-2-LC
// hand-written proof input the class-1 two-build proof compares every
// leg's own regeneration against BEFORE comparing anything else, so a leg
// that regenerates (or is handed) a different-bytes fixture fails loudly,
// by name, with both digests printed -- rather than silently comparing a
// different file and passing vacuously (this project's own "every gate
// self-tests" convention, cited throughout 06-CONTEXT.md).
//
// Originally local to tests/unit/test_gen_he_aac.cpp (06-02); promoted here
// (06-05) so tests/integration/test_audio_hash_decoder.cpp's own two-build
// proof can call it too -- tests/unit/ and tests/integration/ are SEPARATE
// binaries (mediadiff_unit_tests / mediadiff_integration_tests), so an
// `extern` prototype alone would not link across them. Mirrors
// tests/support/mutate.{h,cpp}'s own precedent: header-only declarations,
// implementation in the paired .cpp, linked into BOTH test targets.

#include <string>

namespace mediadiff::test {

// Computed directly against tests/fixtures/audio_aac_handwritten.mp4's real
// generated bytes (a throwaway XXH3_128bits() call, linked against this
// project's own vcpkg-installed libxxhash) -- never guessed, never
// re-derived from tools/gen_he_aac.py's own Python side alone.
inline constexpr const char* kAudioAacHandwrittenXxh3_128 = "64b5439769abd59b7130282d5a18cb4a";

// Computes `fixture_path`'s actual XXH3-128 and compares it against
// kAudioAacHandwrittenXxh3_128, returning both digests via out-params so a
// caller can report a failure BY NAME with both values printed, rather than
// a bare boolean.
bool assert_aac_handwritten_input_identity(const std::string& fixture_path, std::string& out_expected,
                                            std::string& out_actual);

}  // namespace mediadiff::test
