#pragma once

#include <CLI/CLI.hpp>

namespace mediadiff {

// Registers the `explain <check.id>` subcommand (ENG-13, DOC-02): prints
// the compiled-in docs/checks/<id>.md body the build embedded for `id`
// (src/core/check_explain.h's explain_doc, generated by
// tools/gen_registry.py) -- the three fixed sections in order (what it
// measures, why it matters, accept/tune/silence, the last already
// carrying its own three labelled sub-parts verbatim). Resolves `id`
// through the registry first, then the alias table (an alias hit prints a
// deprecation line naming the current id before the documentation); an
// unresolvable id is a usage error (exit 64) naming the id, plus -- when
// its first dot-segment matches a registered check's own CheckDef::group
// -- a listing of that group's check ids.
void register_explain_command(CLI::App& app);

}  // namespace mediadiff
