// PROBE-06 (03-07-PLAN.md Tasks 1-2): ts_scan's bounded stride-autodetected
// packet walk -- stride detection (188/192/204), resync after corruption,
// the structurally-bounded per-PID table, PCR extraction, PAT/PMT parsing
// with version tracking, and the mux-rate estimate. Behaviors requiring an
// exact hand-computed value (stride confirmation failure, malformed
// adaptation fields, malformed PSI sections, the PCR arithmetic itself)
// use hand-constructed byte buffers built directly in this file, per this
// plan's own instruction; the rest read real fixtures generated by
// scripts/gen_corpus.sh. PROBE-07's continuity-counter carve-outs have
// their own dedicated hand-verified table in test_ts_continuity.cpp.

#include <catch2/catch_test_macros.hpp>

#include <atomic>
#include <chrono>
#include <cstdint>
#include <filesystem>
#include <fstream>
#include <string>
#include <vector>

#include "probe/ts_scan.h"
#include "support/fixture_paths.h"

using mediadiff::kNullPid;
using mediadiff::kPidCount;
using mediadiff::run_ts_scan;
using mediadiff::TsScanResult;

namespace {

namespace fs = std::filesystem;

fs::path unique_scratch_dir() {
  static std::atomic<int> counter{0};
  const auto now = std::chrono::steady_clock::now().time_since_epoch().count();
  const fs::path dir =
      fs::temp_directory_path() / ("mediadiff_ts_scan_" + std::to_string(now) + "_" + std::to_string(counter++));
  std::error_code ec;
  fs::create_directories(dir, ec);
  return dir;
}

std::string write_bytes(const std::string& name, const std::string& bytes) {
  const fs::path path = unique_scratch_dir() / name;
  std::ofstream out(path, std::ios::binary);
  REQUIRE(out.is_open());
  out.write(bytes.data(), static_cast<std::streamsize>(bytes.size()));
  out.close();
  return path.string();
}

std::string fixture(const std::string& name) { return mediadiff::test::fixture_dir() + "/" + name; }

// Builds one syntactically minimal 188-byte TS packet: sync(1) + header
// bytes (transport_error=0, payload_start, pid) + scrambling/af_control/cc,
// no adaptation field, payload padded to fill the remaining 184 bytes.
// `pusi` is payload_unit_start_indicator; `payload_prefix` (if non-empty) is
// placed at the very start of the payload (e.g. a PSI pointer_field +
// section), the rest padded with 0xFF stuffing.
std::string build_packet(int pid, std::uint8_t cc, bool pusi, const std::string& payload_prefix = "",
                          std::uint8_t af_control = 0x1, const std::string& adaptation_field = "") {
  std::string packet;
  packet.push_back(static_cast<char>(0x47));
  const std::uint8_t b1 = static_cast<std::uint8_t>((pusi ? 0x40 : 0x00) | ((pid >> 8) & 0x1F));
  packet.push_back(static_cast<char>(b1));
  packet.push_back(static_cast<char>(pid & 0xFF));
  const std::uint8_t b3 = static_cast<std::uint8_t>((af_control << 4) | (cc & 0x0F));
  packet.push_back(static_cast<char>(b3));
  if (af_control == 0x2 || af_control == 0x3) {
    packet.push_back(static_cast<char>(adaptation_field.size()));
    packet += adaptation_field;
  }
  packet += payload_prefix;
  packet.resize(188, static_cast<char>(0xFF));
  REQUIRE(packet.size() == 188);
  return packet;
}

std::string be16(int v) {
  std::string s(2, '\0');
  s[0] = static_cast<char>((v >> 8) & 0xFF);
  s[1] = static_cast<char>(v & 0xFF);
  return s;
}

// Stride detection requires kStrideConfirmCount (5) consecutive sync bytes
// -- every hand-built buffer below that constructs fewer than 5 packets of
// its own pads out to 5 with plain payload-only filler packets on a PID
// none of these tests inspect, purely so `stride == 188` is confirmable at
// all before the behavior under test can be observed.
std::string pad_to_min_packets(const std::string& buf, int min_packets) {
  std::string padded = buf;
  int have = static_cast<int>(buf.size() / 188);
  for (int i = have; i < min_packets; ++i) {
    padded += build_packet(0x0199, static_cast<std::uint8_t>(i), /*pusi=*/false);
  }
  return padded;
}

}  // namespace

// --- Task 1 Behavior 1: 188/192/204-byte stride detection -----------------

TEST_CASE("ts_scan - a 188-byte-stride stream is detected as stride 188", "[unit]") {
  const auto result = run_ts_scan(fixture("ts_single.ts"));
  REQUIRE(result.has_value());
  REQUIRE(result->complete);
  REQUIRE(result->stride == 188);
}

TEST_CASE("ts_scan - a 192-byte-stride stream (4-byte timestamp prefix) is detected as stride 192", "[unit]") {
  const auto result = run_ts_scan(fixture("ts_192.ts"));
  REQUIRE(result.has_value());
  REQUIRE(result->complete);
  REQUIRE(result->stride == 192);
}

TEST_CASE("ts_scan - a 204-byte-stride stream (16-byte FEC suffix) is detected as stride 204", "[unit]") {
  const auto result = run_ts_scan(fixture("ts_204.ts"));
  REQUIRE(result.has_value());
  REQUIRE(result->complete);
  REQUIRE(result->stride == 204);
}

// --- Task 1 Behavior 2: stride detection requires multi-sync confirmation -

TEST_CASE("ts_scan - a single stray 0x47 with no confirming sync bytes detects no stride", "[unit]") {
  // 2000 zero bytes with a single 0x47 at offset 0 -- no other byte in the
  // buffer is 0x47, so no candidate (stride, start_offset) pair can ever
  // reach the required kStrideConfirmCount confirmations.
  std::string buf(2000, '\x00');
  buf[0] = static_cast<char>(0x47);
  const auto result = run_ts_scan(write_bytes("single_sync.bin", buf));
  REQUIRE(result.has_value());
  REQUIRE_FALSE(result->complete);
  REQUIRE(result->stop_offset == 0);
}

// --- Task 1 Behavior 3: resync after a corrupted mid-stream region --------

TEST_CASE("ts_scan - resyncs after a corrupted mid-stream region and records bytes skipped", "[unit]") {
  const auto result = run_ts_scan(fixture("ts_ccgap.ts"));
  REQUIRE(result.has_value());
  REQUIRE(result->complete);
  REQUIRE(result->stride == 188);
  REQUIRE(result->resync_bytes_skipped > 0);
}

// --- Task 1 Behavior 4: exact packet-accounting identity ------------------

TEST_CASE("ts_scan - per-PID packet counts plus null_packets sum exactly to total_packets", "[unit]") {
  const auto result = run_ts_scan(fixture("ts_multiprogram.ts"));
  REQUIRE(result.has_value());
  REQUIRE(result->complete);
  std::int64_t sum = result->null_packets;
  for (int pid = 0; pid < kPidCount; ++pid) {
    sum += result->pid_stats(pid).packets;
  }
  REQUIRE(sum == result->total_packets);
  REQUIRE(result->total_packets > 0);
}

// --- Task 1 Behavior 5: the PID table is a fixed, bounded structure -------

TEST_CASE("ts_scan - a stream cycling through every possible PID does not grow an unbounded allocation", "[unit]") {
  // 8192 packets, one per possible PID value (0..8191), each with payload
  // present and cc=0 (each a distinct PID's first-ever packet, so no CC
  // error is possible) -- proves the per-PID table is addressable across
  // the FULL domain without any dynamic growth or crash.
  std::string buf;
  buf.reserve(static_cast<std::size_t>(kPidCount) * 188);
  for (int pid = 0; pid < kPidCount; ++pid) {
    buf += build_packet(pid, 0, /*pusi=*/false);
  }
  const auto result = run_ts_scan(write_bytes("all_pids.bin", buf));
  REQUIRE(result.has_value());
  REQUIRE(result->complete);
  REQUIRE(result->stride == 188);
  // Every real PID (all except 0x1FFF, which is the reserved null PID) saw
  // exactly one packet; 0x1FFF was counted as a null packet instead.
  for (int pid = 0; pid < kPidCount; ++pid) {
    if (pid == kNullPid) {
      continue;
    }
    REQUIRE(result->pid_stats(pid).packets == 1);
  }
  REQUIRE(result->null_packets == 1);
  REQUIRE(result->total_packets == kPidCount);
}

// --- Task 1 Behavior 6: scrambling-control values are recorded per PID ----

TEST_CASE("ts_scan - a non-zero transport_scrambling_control value is recorded, not silently treated as clear",
          "[unit]") {
  std::string buf;
  // Five confirming packets on PID 0x0100 so the file's own sync stride is
  // unambiguous, the last one carrying a non-zero scrambling value (0b10,
  // "scrambled with even key").
  for (int i = 0; i < 4; ++i) {
    buf += build_packet(0x0100, static_cast<std::uint8_t>(i), /*pusi=*/false);
  }
  std::string scrambled = build_packet(0x0100, 4, /*pusi=*/false);
  scrambled[3] = static_cast<char>(static_cast<std::uint8_t>(scrambled[3]) | 0x80);  // scrambling bits = 0b10
  buf += scrambled;

  const auto result = run_ts_scan(write_bytes("scrambled.bin", buf));
  REQUIRE(result.has_value());
  REQUIRE(result->complete);
  const auto& stats = result->pid_stats(0x0100);
  REQUIRE((stats.scrambling_seen_mask & (1u << 0)) != 0);  // clear packets also seen
  REQUIRE((stats.scrambling_seen_mask & (1u << 2)) != 0);  // 0b10 recorded
}

// --- Task 1 Behavior 7: an oversized adaptation_field_length is malformed,
//     not an out-of-bounds read --------------------------------------------

TEST_CASE("ts_scan - an adaptation_field_length exceeding the packet's own remaining bytes is malformed, never "
          "read past",
          "[unit]") {
  std::string packet = build_packet(0x0100, 0, /*pusi=*/false, "", 0x3, "");
  // Overwrite the adaptation_field_length byte (index 4) with a value that
  // cannot possibly fit in the 183 bytes actually available.
  packet[4] = static_cast<char>(255);
  const auto result = run_ts_scan(write_bytes("bad_af_len.bin", packet + build_packet(0x0100, 1, false) +
                                                                       build_packet(0x0100, 2, false) +
                                                                       build_packet(0x0100, 3, false) +
                                                                       build_packet(0x0100, 4, false)));
  REQUIRE(result.has_value());
  REQUIRE(result->complete);
  REQUIRE(result->malformed_packets >= 1);
  REQUIRE(result->total_packets == 5);
}

// --- Task 2 Behavior 1: PCR extraction is bit-exact ------------------------

TEST_CASE("ts_scan - PCR extraction equals base*300 + extension in 27 MHz ticks, reserved bits skipped", "[unit]") {
  // A hand-computed PCR: base = 0x1_2345_6789 (33 bits, fits since top bit
  // of the 33-bit domain is bit 32), extension = 0x1AB (9 bits). Encoded
  // per the wire layout: byte0..3 = bits 32..1 of base, byte4 = (bit0 of
  // base)<<7 | 6 reserved bits (all set to 1, as real muxers do) | bit8 of
  // extension, byte5 = low 8 bits of extension.
  const std::uint64_t base = 0x123456789ULL & 0x1FFFFFFFFULL;  // 33-bit value
  const std::uint64_t extension = 0x1AB & 0x1FF;               // 9-bit value
  std::string pcr_field(6, '\0');
  pcr_field[0] = static_cast<char>((base >> 25) & 0xFF);
  pcr_field[1] = static_cast<char>((base >> 17) & 0xFF);
  pcr_field[2] = static_cast<char>((base >> 9) & 0xFF);
  pcr_field[3] = static_cast<char>((base >> 1) & 0xFF);
  const std::uint8_t base_bit0 = static_cast<std::uint8_t>(base & 0x1);
  const std::uint8_t reserved6 = 0x3F;  // all-ones, as real muxers emit
  const std::uint8_t ext_bit8 = static_cast<std::uint8_t>((extension >> 8) & 0x1);
  pcr_field[4] = static_cast<char>(static_cast<std::uint8_t>((base_bit0 << 7) | (reserved6 << 1) | ext_bit8));
  pcr_field[5] = static_cast<char>(extension & 0xFF);

  // adaptation field: flags byte (PCR_flag set) + 6-byte PCR field.
  std::string af;
  af.push_back(static_cast<char>(0x10));  // PCR_flag only
  af += pcr_field;

  std::string packet = build_packet(0x0100, 0, /*pusi=*/false, "", 0x3, af);

  const auto result = run_ts_scan(write_bytes("pcr_exact.bin", packet + build_packet(0x0100, 1, false) +
                                                                       build_packet(0x0100, 2, false) +
                                                                       build_packet(0x0100, 3, false) +
                                                                       build_packet(0x0100, 4, false)));
  REQUIRE(result.has_value());
  REQUIRE(result->complete);
  REQUIRE(result->pcr_samples.size() == 1);
  const std::int64_t expected_ticks = static_cast<std::int64_t>(base) * 300 + static_cast<std::int64_t>(extension);
  REQUIRE(result->pcr_samples[0].ticks == expected_ticks);
  REQUIRE(result->pcr_samples[0].pid == 0x0100);
  REQUIRE(result->pcr_samples[0].offset == 0);
}

// --- Task 2 Behavior 2: PCR_flag=0 yields no PCR; a too-short adaptation
//     field with PCR_flag=1 yields no PCR and is malformed -----------------

TEST_CASE("ts_scan - PCR_flag=0 yields no PCR for that packet", "[unit]") {
  std::string af;
  af.push_back(static_cast<char>(0x00));  // no flags set
  std::string packet = build_packet(0x0100, 0, /*pusi=*/false, "", 0x3, af);
  const auto result = run_ts_scan(write_bytes("no_pcr_flag.bin", packet + build_packet(0x0100, 1, false) +
                                                                         build_packet(0x0100, 2, false) +
                                                                         build_packet(0x0100, 3, false) +
                                                                         build_packet(0x0100, 4, false)));
  REQUIRE(result.has_value());
  REQUIRE(result->complete);
  REQUIRE(result->pcr_samples.empty());
}

TEST_CASE("ts_scan - PCR_flag=1 with too few declared bytes yields no PCR and is malformed", "[unit]") {
  std::string af;
  af.push_back(static_cast<char>(0x10));  // PCR_flag set
  af += std::string(3, '\0');             // only 3 bytes follow -- PCR needs 6
  std::string packet = build_packet(0x0100, 0, /*pusi=*/false, "", 0x3, af);
  const auto result = run_ts_scan(write_bytes("short_pcr.bin", packet + build_packet(0x0100, 1, false) +
                                                                       build_packet(0x0100, 2, false) +
                                                                       build_packet(0x0100, 3, false) +
                                                                       build_packet(0x0100, 4, false)));
  REQUIRE(result.has_value());
  REQUIRE(result->complete);
  REQUIRE(result->pcr_samples.empty());
  REQUIRE(result->malformed_packets >= 1);
}

// --- Task 2 Behavior 3: each PCR carries its packet's byte offset ---------

TEST_CASE("ts_scan - a real file's PCR samples each carry the correct packet byte offset", "[unit]") {
  const auto result = run_ts_scan(fixture("ts_single.ts"));
  REQUIRE(result.has_value());
  REQUIRE(result->complete);
  REQUIRE_FALSE(result->pcr_samples.empty());
  for (const auto& sample : result->pcr_samples) {
    REQUIRE(sample.offset >= 0);
    REQUIRE(sample.offset % result->stride == 0);
  }
}

// --- Task 2 Behavior 4: PAT yields the program-number-to-PMT-PID map ------

TEST_CASE("ts_scan - a single-program TS's PAT yields exactly one program entry", "[unit]") {
  const auto result = run_ts_scan(fixture("ts_single.ts"));
  REQUIRE(result.has_value());
  REQUIRE(result->complete);
  REQUIRE(result->programs.size() == 1);
  REQUIRE(result->programs[0].program_number == 1);
  REQUIRE(result->programs[0].pmt_pid > 0);
  REQUIRE_FALSE(result->pat_offsets.empty());
}

TEST_CASE("ts_scan - a two-program TS's PAT yields two program entries with correct program numbers", "[unit]") {
  const auto result = run_ts_scan(fixture("ts_multiprogram.ts"));
  REQUIRE(result.has_value());
  REQUIRE(result->complete);
  REQUIRE(result->programs.size() == 2);
  std::vector<int> program_numbers;
  for (const auto& program : result->programs) {
    program_numbers.push_back(program.program_number);
  }
  REQUIRE(program_numbers.size() == 2);
  REQUIRE(program_numbers[0] != program_numbers[1]);
}

// --- Task 2 Behavior 5: PMT yields version_number, PCR_PID, ES PIDs; a
//     version bump counts as exactly one change -----------------------------

TEST_CASE("ts_scan - a real file's PMT yields version_number, PCR_PID and a non-empty ES PID list", "[unit]") {
  const auto result = run_ts_scan(fixture("ts_single.ts"));
  REQUIRE(result.has_value());
  REQUIRE(result->complete);
  REQUIRE(result->programs.size() == 1);
  const auto& program = result->programs[0];
  REQUIRE(program.version_number.has_value());
  REQUIRE(program.pcr_pid.has_value());
  REQUIRE_FALSE(program.es_pids.empty());
  REQUIRE_FALSE(program.pmt_offsets.empty());
  // Repeated re-sends of the SAME version never count as a change (first
  // sighting establishes the baseline).
  REQUIRE(program.version_changes == 0);
}

TEST_CASE("ts_scan - a PMT re-sent with an incremented version_number counts exactly one change", "[unit]") {
  // Hand-built: PAT naming program 1 -> PMT PID 0x1000, then two PMT
  // sections on that PID at version 0 and version 1 (first sighting is the
  // baseline, the second is the one real change).
  auto build_pat = [](std::uint8_t cc) {
    std::string section;
    section.push_back(static_cast<char>(0x00));  // table_id = PAT
    // section_length filled below; transport_stream_id(2) + ver/cni(1) +
    // section_number(1) + last_section_number(1) + one program entry(4) +
    // CRC(4) = 13 bytes after the length field.
    const int section_length = 13;
    std::string header = be16(0xB000 | section_length);  // syntax indicator + reserved '11' + length
    std::string fixed = std::string("\x00\x01", 2) + std::string("\xC1", 1) + std::string("\x00", 1) +
                         std::string("\x00", 1);  // transport_stream_id, ver/cni, section#, last_section#
    std::string program_entry = be16(1) + std::string(1, static_cast<char>(0xE0 | ((0x1000 >> 8) & 0x1F))) +
                                 std::string(1, static_cast<char>(0x1000 & 0xFF));
    std::string crc(4, '\0');
    std::string full_section = section + header + fixed + program_entry + crc;
    return build_packet(0x0000, cc, /*pusi=*/true, std::string(1, '\x00') + full_section);
  };
  auto build_pmt = [](std::uint8_t cc, int version) {
    std::string section;
    section.push_back(static_cast<char>(0x02));  // table_id = PMT
    const int section_length = 13;                // 9 fixed + 0 descriptors + 0 ES entries + 4 CRC
    std::string header = be16(0xB000 | section_length);
    std::string program_number = be16(1);
    std::string ver_cni = std::string(1, static_cast<char>(0xC1 | ((version & 0x1F) << 1)));
    std::string secnum(1, '\x00');
    std::string last_secnum(1, '\x00');
    std::string pcr_pid_field = std::string(1, static_cast<char>(0xE0 | ((0x0101 >> 8) & 0x1F))) +
                                 std::string(1, static_cast<char>(0x0101 & 0xFF));
    std::string program_info_length = be16(0xF000);
    std::string crc(4, '\0');
    std::string full_section =
        section + header + program_number + ver_cni + secnum + last_secnum + pcr_pid_field + program_info_length + crc;
    return build_packet(0x1000, cc, /*pusi=*/true, std::string(1, '\x00') + full_section);
  };

  const std::string buf = pad_to_min_packets(build_pat(0) + build_pmt(0, 0) + build_pmt(1, 1), 5);
  const auto result = run_ts_scan(write_bytes("pmt_version_bump.bin", buf));
  REQUIRE(result.has_value());
  REQUIRE(result->complete);
  REQUIRE(result->programs.size() == 1);
  REQUIRE(result->programs[0].version_number.has_value());
  REQUIRE(*result->programs[0].version_number == 1);
  REQUIRE(result->programs[0].version_changes == 1);
  REQUIRE(result->programs[0].pmt_offsets.size() == 2);
}

// --- Task 2 Behavior 6: PAT/PMT section repetition offsets are recorded ---

TEST_CASE("ts_scan - PAT and PMT section repetition byte offsets are all recorded, not just the first", "[unit]") {
  const auto result = run_ts_scan(fixture("ts_single.ts"));
  REQUIRE(result.has_value());
  REQUIRE(result->complete);
  REQUIRE(result->pat_offsets.size() > 1);
  REQUIRE(result->programs.size() == 1);
  REQUIRE(result->programs[0].pmt_offsets.size() > 1);
}

// --- Task 2 Behavior 7/8: the mux-rate estimate --------------------------

TEST_CASE("ts_scan - the mux-rate estimate matches the exact integer formula from two consecutive PCRs", "[unit]") {
  const auto result = run_ts_scan(fixture("ts_single.ts"));
  REQUIRE(result.has_value());
  REQUIRE(result->complete);
  REQUIRE(result->pcr_samples.size() >= 2);
  REQUIRE(result->mux_rate.has_value());
  REQUIRE(result->mux_rate->estimated);
  REQUIRE(result->mux_rate->bytes_per_second_den > 0);
  REQUIRE(result->mux_rate->bytes_per_second_num > 0);

  // Recompute from the first two same-pid samples and confirm the exact
  // formula.
  const auto& s0 = result->pcr_samples[0];
  const auto& s1 = result->pcr_samples[1];
  REQUIRE(s0.pid == s1.pid);
  const std::int64_t pcr_delta = s1.ticks - s0.ticks;
  const std::int64_t offset_delta = s1.offset - s0.offset;
  REQUIRE(pcr_delta > 0);
  // 03-08-PLAN.md Rule 1 fix: this formula previously carried an erroneous
  // `* 8` bytes-to-bits factor, contradicting the field's own name and
  // ts_scan.h's documented bytes/sec contract (which 03-08-PLAN.md's own
  // byte-offset-to-milliseconds conversion consumes directly as bytes/sec)
  // -- caught when a real fixture's independently-computed PCR spacing
  // came back exactly 8x this scanner's own reported value.
  const std::int64_t expected_num = offset_delta * 27000000;
  REQUIRE(result->mux_rate->bytes_per_second_num == expected_num);
  REQUIRE(result->mux_rate->bytes_per_second_den == pcr_delta);
}

TEST_CASE("ts_scan - a non-positive PCR delta pair is skipped and does not produce an estimate for that pair",
          "[unit]") {
  std::string af0;
  af0.push_back(static_cast<char>(0x10));
  af0 += std::string("\x00\x00\x00\x00\x00\x64", 6);  // base=0, extension small -> tiny positive ticks
  std::string af1;
  af1.push_back(static_cast<char>(0x10));
  af1 += std::string("\x00\x00\x00\x00\x00\x32", 6);  // extension smaller -> ticks decreases (negative delta)

  const std::string buf =
      pad_to_min_packets(build_packet(0x0100, 0, false, "", 0x3, af0) + build_packet(0x0100, 1, false, "", 0x3, af1), 5);
  const auto result = run_ts_scan(write_bytes("nonpositive_pcr_delta.bin", buf));
  REQUIRE(result.has_value());
  REQUIRE(result->complete);
  REQUIRE(result->pcr_samples.size() == 2);
  REQUIRE_FALSE(result->mux_rate.has_value());
}

TEST_CASE("ts_scan - fewer than two PCRs yields no mux-rate estimate at all, not a zero", "[unit]") {
  std::string af;
  af.push_back(static_cast<char>(0x10));
  af += std::string("\x00\x00\x00\x00\x00\x64", 6);
  const std::string buf = pad_to_min_packets(build_packet(0x0100, 0, false, "", 0x3, af) + build_packet(0x0100, 1, false), 5);
  const auto result = run_ts_scan(write_bytes("single_pcr.bin", buf));
  REQUIRE(result.has_value());
  REQUIRE(result->complete);
  REQUIRE(result->pcr_samples.size() == 1);
  REQUIRE_FALSE(result->mux_rate.has_value());
}

// --- Task 2 Behavior 9: oversized section_length is discarded, not read
//     past ------------------------------------------------------------------

TEST_CASE("ts_scan - a section_length larger than the available bytes is discarded, never read past", "[unit]") {
  std::string section;
  section.push_back(static_cast<char>(0x00));  // PAT
  section += be16(0xB000 | 0x0FFF);            // section_length declared as the 12-bit max -- cannot possibly fit
  const std::string buf =
      pad_to_min_packets(build_packet(0x0000, 0, /*pusi=*/true, std::string(1, '\x00') + section), 5);
  const auto result = run_ts_scan(write_bytes("oversized_section.bin", buf));
  REQUIRE(result.has_value());
  REQUIRE(result->complete);
  REQUIRE(result->discarded_sections >= 1);
  REQUIRE(result->programs.empty());
}

// --- Libav-independence / input_open behavior -----------------------------

TEST_CASE("ts_scan - a missing file returns Error::input_open, never a crash", "[unit]") {
  const auto result = run_ts_scan("/nonexistent/path/does/not/exist.ts");
  REQUIRE_FALSE(result.has_value());
}
