// 06-02-PLAN.md Task 1 (AUDIO-03, D-10, D-11): coverage for
// tools/gen_he_aac.py's hand-written HE-AAC explicit/implicit signaling
// pair and the non-silent class-1 two-build proof input
// (audio_aac_handwritten.mp4).
//
// D-11's own requirement: the class-1 two-build proof (06-05) must assert
// this fixture's own XXH3-128 against a RECORDED input-identity constant
// BEFORE comparing anything else, so a leg that regenerates (or is handed)
// a different-bytes fixture fails loudly, by name, with both digests
// printed -- rather than silently comparing a different file and passing
// vacuously (this project's own "every gate self-tests" convention, cited
// throughout 06-CONTEXT.md). `assert_aac_handwritten_input_identity()`
// below is that assertion helper, declared with external linkage
// (deliberately not `static`/anonymous-namespace) so 06-05's own
// two-build test can call it directly -- no shared header exists for it
// yet (this plan's own `files_modified` list names only this one
// translation unit), so 06-05 declares its own `extern` prototype
// matching the signature below, or promotes this pair into a small shared
// header at that point; either is a 06-05 decision, not this plan's.
//
// `kAudioAacHandwrittenXxh3_128` was computed directly against this
// fixture's real generated bytes (a throwaway XXH3_128bits() call, linked
// against this project's own vcpkg-installed libxxhash, over
// tests/fixtures/audio_aac_handwritten.mp4 as produced by
// `scripts/gen_corpus.sh` on this workstation) -- never guessed, never
// re-derived from the generator's Python side alone. `mediadiff snapshot`'s
// own `input_identity` field is not yet populated by any analyzer as of
// this plan (it is one of `src/core/model.h`'s fields "grown a phase
// early," per 06-CONTEXT.md's Established Patterns), so it is not yet an
// available cross-check oracle for this constant.

#include <catch2/catch_test_macros.hpp>

#include <cstdint>
#include <fstream>
#include <ios>
#include <string>
#include <vector>

#include <fmt/format.h>
#include <xxhash.h>

#include "support/fixture_paths.h"

namespace {

std::string audio_aac_handwritten_mp4() { return mediadiff::test::fixture_dir() + "/audio_aac_handwritten.mp4"; }

std::vector<std::uint8_t> read_file_bytes(const std::string& path) {
  std::ifstream f(path, std::ios::binary | std::ios::ate);
  if (!f) {
    return {};
  }
  const std::streamsize size = f.tellg();
  f.seekg(0, std::ios::beg);
  std::vector<std::uint8_t> buf(static_cast<std::size_t>(size));
  if (size > 0) {
    f.read(reinterpret_cast<char*>(buf.data()), size);
  }
  return buf;
}

std::string xxh3_128_hex(const std::vector<std::uint8_t>& data) {
  const XXH128_hash_t digest = XXH3_128bits(data.data(), data.size());
  return fmt::format("{:016x}{:016x}", digest.high64, digest.low64);
}

}  // namespace

// D-11's recorded input identity for audio_aac_handwritten.mp4 -- the
// non-silent, non-SBR, plain-AOT-2-LC hand-written proof input the class-1
// two-build proof (06-05) compares every leg's own regeneration against.
const char* const kAudioAacHandwrittenXxh3_128 = "64b5439769abd59b7130282d5a18cb4a";

// Exported assertion helper (external linkage, see the file header comment
// above): computes audio_aac_handwritten.mp4's ACTUAL XXH3-128 and
// compares it against kAudioAacHandwrittenXxh3_128, returning both digests
// via out-params so a caller (this file's own TEST_CASE below, and 06-05's
// two-build proof later) can report a failure BY NAME with both values
// printed, rather than a bare boolean.
bool assert_aac_handwritten_input_identity(const std::string& fixture_path, std::string& out_expected,
                                            std::string& out_actual) {
  out_expected = kAudioAacHandwrittenXxh3_128;
  const std::vector<std::uint8_t> bytes = read_file_bytes(fixture_path);
  out_actual = bytes.empty() ? std::string("<file not found or empty>") : xxh3_128_hex(bytes);
  return out_actual == out_expected;
}

// Test: audio_aac_handwritten.mp4's own XXH3-128 matches the recorded
// input-identity constant -- a leg producing different bytes fails HERE,
// by name, with both digests printed, rather than a 06-05 two-build
// comparison silently comparing two different files (D-11).
TEST_CASE("unit.gen_he_aac - audio_aac_handwritten.mp4 matches its recorded input identity", "[unit]") {
  std::string expected;
  std::string actual;
  const bool matched = assert_aac_handwritten_input_identity(audio_aac_handwritten_mp4(), expected, actual);
  INFO("expected XXH3-128: " << expected);
  INFO("actual   XXH3-128: " << actual);
  REQUIRE(matched);
}

// Test: the byte-identical DOC-03 clean-pair copy carries the SAME input
// identity as the original -- both are the generator's own second
// emission of identical bytes (Test 4's determinism guarantee), not a
// `cp`-style file-system copy standing in for a real proof.
TEST_CASE("unit.gen_he_aac - audio_aac_handwritten_copy.mp4 shares the same input identity", "[unit]") {
  const std::string copy_path = mediadiff::test::fixture_dir() + "/audio_aac_handwritten_copy.mp4";
  std::string expected;
  std::string actual;
  const bool matched = assert_aac_handwritten_input_identity(copy_path, expected, actual);
  INFO("expected XXH3-128: " << expected);
  INFO("actual   XXH3-128: " << actual);
  REQUIRE(matched);
}
